### ISSUE TITLE
main-thread-to-audioworklet doesn't work on Safari

### ISSUE THREAD

**Issue by ebekebe** [padenot/ringbuf.js#14]
I tried to run main-thread-to-audioworklet on Safari 15.4 on macOS with `__XPC_JSC_useSharedArrayBuffer=1`, but it doesn't work. Is that a known limitation of Safari?

**Comment by padenot** [comment]
Real strange, this used to work. `console.log` from the worklet doesn't work either.

**Comment by chaosprint** [comment]
> Real strange, this used to work. `console.log` from the worklet doesn't work either.

I got this problem too. Safari version 15.2

**Comment by designerfuzzi** [comment]
to be able to work an class named "SharedArrayBuffer" should exist, which is nowhere to find.. 
should it not be "new Ringbuffer(...)" instead?

**Comment by EricTetz** [comment]
@designerfuzzi  If `SharedArrayBuffer` is missing it's because the file was served with the wrong headers ([see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes)).

I'm seeing the everything get instantiated correctly, the `AudioContext` change status to "running", the `AudioWorkletNode` gets loaded (its script is loaded and shows up in the debugger), and Safari even shows a icon in the URL bar (e.g. 🔊) to indicate that the tab is making sound.  Just... nothing comes out. The `AudioWorkletNode` is not pulling data from the ring buffer, so it gets full and then is never written to again.

**Comment by EricTetz** [comment]
FYI, I just checked in a newer version of Safari and this is working again. Yeah!

**Comment by ebekebe** [comment]
@EricTetz that is great news, so I am going to close this issue.

**Comment by padenot** [comment]
Thanks for checking folks, glad this is working. I'll be updating the readme.

**Comment by designerfuzzi** [comment]
SharedArrayBuffer is supported from Safari 15.2. every earlier version will just do nothing of course.
https://caniuse.com/sharedarraybuffer
